INFO 2025-09-19 15:25:40,252 autoreload 90216 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 17:39:36,214 autoreload 40542 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 17:41:47,337 autoreload 40542 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/config/settings.py changed, reloading.
INFO 2025-09-20 17:49:53,376 autoreload 43903 8371577024 Watching for file changes with StatReloader
WARNING 2025-09-20 17:50:14,076 log 43903 6191083520 Method Not Allowed: /api/v1/auth/register/
WARNING 2025-09-20 17:50:14,077 basehttp 43903 6191083520 "GET /api/v1/auth/register/ HTTP/1.1" 405 40
ERROR 2025-09-20 17:50:20,809 log 43903 6191083520 Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/views.py", line 32, in create
    'user': UserProfileSerializer(user).data,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/serializers.py", line 88, in get_posts_count
    return obj.posts.count()
           ^^^^^^^^^
AttributeError: 'User' object has no attribute 'posts'
ERROR 2025-09-20 17:50:20,814 basehttp 43903 6191083520 "POST /api/v1/auth/register/ HTTP/1.1" 500 140087
INFO 2025-09-20 17:53:54,693 autoreload 43903 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/serializers.py changed, reloading.
INFO 2025-09-20 17:53:56,185 autoreload 45184 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 17:54:43,341 basehttp 45184 6190903296 "POST /api/v1/auth/register/ HTTP/1.1" 201 766
INFO 2025-09-20 18:00:55,506 basehttp 45184 6207729664 "POST /api/v1/auth/login/ HTTP/1.1" 200 761
INFO 2025-09-20 18:03:54,504 basehttp 45184 6224556032 "GET /api/v1/auth/profile/ HTTP/1.1" 200 228
INFO 2025-09-20 18:09:56,437 autoreload 45184 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/admin.py changed, reloading.
INFO 2025-09-20 18:09:57,060 autoreload 50134 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 18:17:11,512 autoreload 50134 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/admin.py changed, reloading.
INFO 2025-09-20 18:17:12,455 autoreload 52341 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 18:17:32,923 autoreload 52341 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/admin.py changed, reloading.
INFO 2025-09-20 18:17:33,320 autoreload 52463 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 18:17:46,803 autoreload 52463 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/admin.py changed, reloading.
INFO 2025-09-20 18:17:47,191 autoreload 52544 8371577024 Watching for file changes with StatReloader
INFO 2025-09-20 18:21:42,297 autoreload 53778 8371577024 Watching for file changes with StatReloader
WARNING 2025-09-20 18:21:51,922 log 53778 6138966016 Not Found: /
WARNING 2025-09-20 18:21:51,924 basehttp 53778 6138966016 "GET / HTTP/1.1" 404 2651
WARNING 2025-09-20 18:21:52,163 log 53778 6155792384 Not Found: /apple-touch-icon-precomposed.png
WARNING 2025-09-20 18:21:52,166 log 53778 6172618752 Not Found: /apple-touch-icon.png
WARNING 2025-09-20 18:21:52,168 log 53778 6189445120 Not Found: /favicon.ico
WARNING 2025-09-20 18:21:52,169 basehttp 53778 6172618752 "GET /apple-touch-icon.png HTTP/1.1" 404 2729
WARNING 2025-09-20 18:21:52,169 basehttp 53778 6155792384 "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2765
WARNING 2025-09-20 18:21:52,169 basehttp 53778 6189445120 "GET /favicon.ico HTTP/1.1" 404 2702
WARNING 2025-09-20 18:21:52,526 log 53778 6138966016 Not Found: /favicon.ico
WARNING 2025-09-20 18:21:52,528 basehttp 53778 6138966016 "GET /favicon.ico HTTP/1.1" 404 2702
INFO 2025-09-20 18:21:56,695 basehttp 53778 6138966016 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-09-20 18:21:56,736 basehttp 53778 6206271488 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4170
INFO 2025-09-20 18:21:56,751 basehttp 53778 6138966016 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-09-20 18:21:56,752 basehttp 53778 6223097856 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-09-20 18:21:56,774 basehttp 53778 6223097856 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-09-20 18:21:56,776 basehttp 53778 6138966016 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-09-20 18:21:56,778 basehttp 53778 6206271488 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-09-20 18:21:56,783 basehttp 53778 6239924224 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-09-20 18:21:56,784 basehttp 53778 6223097856 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-09-20 18:22:05,868 basehttp 53778 6138966016 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-09-20 18:22:05,906 basehttp 53778 6206271488 "GET /admin/ HTTP/1.1" 200 6597
INFO 2025-09-20 18:22:05,945 basehttp 53778 6239924224 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-09-20 18:22:05,976 basehttp 53778 6138966016 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-09-20 18:22:05,977 basehttp 53778 6223097856 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-09-20 18:22:19,055 basehttp 53778 6239924224 "GET /admin/accounts/user/ HTTP/1.1" 200 13341
INFO 2025-09-20 18:22:19,122 basehttp 53778 6138966016 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-09-20 18:22:19,126 basehttp 53778 6239924224 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-09-20 18:22:19,127 basehttp 53778 6256750592 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-09-20 18:22:19,128 basehttp 53778 6273576960 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-09-20 18:22:19,130 basehttp 53778 6138966016 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-09-20 18:22:19,130 basehttp 53778 6239924224 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-09-20 18:22:19,130 basehttp 53778 6256750592 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-09-20 18:22:19,131 basehttp 53778 6273576960 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-09-20 18:22:19,132 basehttp 53778 6206271488 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-09-20 18:22:19,134 basehttp 53778 6138966016 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-09-20 18:22:19,138 basehttp 53778 6239924224 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-09-20 18:22:19,144 basehttp 53778 6256750592 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-09-20 18:22:19,149 basehttp 53778 6223097856 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-20 18:22:19,225 basehttp 53778 6273576960 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-09-20 18:22:19,227 basehttp 53778 6206271488 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-09-20 18:22:19,238 basehttp 53778 6138966016 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-09-20 18:22:32,896 basehttp 53778 6256750592 "GET /admin/accounts/user/3/change/ HTTP/1.1" 200 23945
INFO 2025-09-20 18:22:32,933 basehttp 53778 6223097856 "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-09-20 18:22:32,936 basehttp 53778 6206271488 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-09-20 18:22:32,958 basehttp 53778 6138966016 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-09-20 18:22:32,960 basehttp 53778 6239924224 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-09-20 18:22:32,962 basehttp 53778 6206271488 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-09-20 18:22:32,962 basehttp 53778 6256750592 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15845
INFO 2025-09-20 18:22:32,962 basehttp 53778 6223097856 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-09-20 18:22:32,963 basehttp 53778 6138966016 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
INFO 2025-09-20 18:22:32,974 basehttp 53778 6273576960 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-20 18:22:33,042 basehttp 53778 6239924224 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-09-20 18:22:33,047 basehttp 53778 6223097856 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-09-20 18:22:33,049 basehttp 53778 6256750592 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-09-21 11:15:45,534 autoreload 85416 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:17:59,258 basehttp 85416 6137933824 "GET /api/v1/posts/categories/ HTTP/1.1" 200 52
WARNING 2025-09-21 11:21:34,445 log 85416 6154760192 Unauthorized: /api/v1/posts/categories/
WARNING 2025-09-21 11:21:34,446 basehttp 85416 6154760192 "POST /api/v1/posts/categories/ HTTP/1.1" 401 172
INFO 2025-09-21 11:24:13,928 basehttp 85416 6171586560 "POST /api/v1/auth/login/ HTTP/1.1" 200 761
INFO 2025-09-21 11:27:35,163 basehttp 85416 6188412928 "POST /api/v1/posts/categories/ HTTP/1.1" 201 158
ERROR 2025-09-21 11:29:43,464 log 85416 6205239296 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 497, in to_internal_value
    for field in fields:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1061, in get_fields
    assert hasattr(self.Meta, 'model'), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Class PostCreateUpdateSerializer missing "Meta.model" attribute
ERROR 2025-09-21 11:29:43,469 basehttp 85416 6205239296 "POST /api/v1/posts/ HTTP/1.1" 500 145423
INFO 2025-09-21 11:32:13,029 autoreload 85416 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:32:13,750 autoreload 90391 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:32:39,110 basehttp 90391 6205616128 "POST /api/v1/posts/ HTTP/1.1" 201 230
ERROR 2025-09-21 11:33:52,834 log 90391 6222442496 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py", line 36, in to_representation
    data = super().to_representation(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    for field in fields:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'comments' was declared on serializer PostListSerializer, but has not been included in the 'fields' option.
ERROR 2025-09-21 11:33:52,840 basehttp 90391 6222442496 "GET /api/v1/posts/ HTTP/1.1" 500 165661
INFO 2025-09-21 11:35:05,820 autoreload 90391 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:35:06,714 autoreload 91308 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:35:26,249 basehttp 91308 6197047296 "GET /api/v1/posts/ HTTP/1.1" 200 458
ERROR 2025-09-21 11:37:44,640 log 91308 6213873664 Internal Server Error: /api/v1/posts/my-first-blog-post/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 286, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/views.py", line 90, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    for field in fields:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'comment_count' was declared on serializer PostDetailSerializer, but has not been included in the 'fields' option.
ERROR 2025-09-21 11:37:44,653 basehttp 91308 6213873664 "GET /api/v1/posts/my-first-blog-post/ HTTP/1.1" 500 157657
INFO 2025-09-21 11:38:05,336 autoreload 91308 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:38:05,956 autoreload 92297 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:40:10,222 autoreload 92297 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:40:10,665 autoreload 92957 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:44:02,367 autoreload 92957 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:44:02,995 autoreload 94169 8371577024 Watching for file changes with StatReloader
ERROR 2025-09-21 11:44:30,483 log 94169 6202568704 Internal Server Error: /api/v1/posts/my-first-blog-post/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 286, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/views.py", line 90, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    for field in fields:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'author_info' was declared on serializer PostDetailSerializer, but has not been included in the 'fields' option.
ERROR 2025-09-21 11:44:30,487 basehttp 94169 6202568704 "GET /api/v1/posts/my-first-blog-post/ HTTP/1.1" 500 157628
INFO 2025-09-21 11:44:58,145 autoreload 94169 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:44:58,712 autoreload 94456 8371577024 Watching for file changes with StatReloader
ERROR 2025-09-21 11:45:00,760 log 94456 6168309760 Internal Server Error: /api/v1/posts/my-first-blog-post/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 286, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/views.py", line 90, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    for field in fields:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'category_info' was declared on serializer PostDetailSerializer, but has not been included in the 'fields' option.
ERROR 2025-09-21 11:45:00,762 basehttp 94456 6168309760 "GET /api/v1/posts/my-first-blog-post/ HTTP/1.1" 500 157686
INFO 2025-09-21 11:45:21,343 autoreload 94456 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:45:22,022 autoreload 94580 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:45:23,437 basehttp 94580 6125858816 "GET /api/v1/posts/my-first-blog-post/ HTTP/1.1" 200 521
INFO 2025-09-21 11:46:17,355 autoreload 94580 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/main/serializers.py changed, reloading.
INFO 2025-09-21 11:46:18,541 autoreload 94889 8371577024 Watching for file changes with StatReloader
INFO 2025-09-21 11:46:22,246 basehttp 94889 6133313536 "GET /api/v1/posts/my-first-blog-post/ HTTP/1.1" 200 521
INFO 2025-09-21 11:47:59,481 basehttp 94889 6150139904 "GET /api/v1/posts/my-first-blog-post/ HTTP/1.1" 200 521
INFO 2025-09-22 06:41:55,501 autoreload 65290 8371577024 Watching for file changes with StatReloader
WARNING 2025-09-22 06:42:56,982 log 65290 6202060800 Unauthorized: /api/v1/comments/
WARNING 2025-09-22 06:42:56,985 basehttp 65290 6202060800 "POST /api/v1/comments/ HTTP/1.1" 401 172
ERROR 2025-09-22 06:45:07,741 log 65290 6218887168 Internal Server Error: /api/v1/auth/login/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "comments" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "comments" WHERE "comments...
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/views.py", line 53, in post
    'user': UserProfileSerializer(user).data,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/accounts/serializers.py", line 98, in get_comments_count
    return obj.comments.count()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "comments" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "comments" WHERE "comments...
                                          ^

ERROR 2025-09-22 06:45:07,751 basehttp 65290 6218887168 "POST /api/v1/auth/login/ HTTP/1.1" 500 197667
INFO 2025-09-22 06:46:09,034 autoreload 66686 8371577024 Watching for file changes with StatReloader
INFO 2025-09-22 06:46:13,261 basehttp 66686 6124253184 "POST /api/v1/auth/login/ HTTP/1.1" 200 761
ERROR 2025-09-22 06:49:50,411 log 66686 6141079552 Internal Server Error: /api/v1/comments/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 497, in to_internal_value
    for field in fields:
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `comment` is not valid for model `Comment` in `apps.comments.serializers.CommentCreateSerializer`.
ERROR 2025-09-22 06:49:50,428 basehttp 66686 6141079552 "POST /api/v1/comments/ HTTP/1.1" 500 162725
INFO 2025-09-22 06:52:16,317 autoreload 66686 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/comments/serializers.py changed, reloading.
INFO 2025-09-22 06:52:18,035 autoreload 68637 8371577024 Watching for file changes with StatReloader
ERROR 2025-09-22 06:52:25,847 log 68637 6134493184 Internal Server Error: /api/v1/comments/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 503, in to_internal_value
    validated_value = validate_method(validated_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/comments/serializers.py", line 37, in validate_post
    if not Post.objects.filter(value.id, status='published').exists():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1523, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable int object
ERROR 2025-09-22 06:52:25,850 basehttp 68637 6134493184 "POST /api/v1/comments/ HTTP/1.1" 500 170574
INFO 2025-09-22 06:53:25,239 autoreload 68637 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/comments/serializers.py changed, reloading.
INFO 2025-09-22 06:53:26,106 autoreload 68994 8371577024 Watching for file changes with StatReloader
INFO 2025-09-22 06:53:49,049 basehttp 68994 6169325568 "POST /api/v1/comments/ HTTP/1.1" 201 137
ERROR 2025-09-22 06:53:57,852 log 68994 6169325568 Internal Server Error: /api/v1/comments/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 1869, in to_representation
    method = getattr(self.parent, self.method_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CommentSerializer' object has no attribute 'get_replies_count'
ERROR 2025-09-22 06:53:57,866 basehttp 68994 6169325568 "GET /api/v1/comments/ HTTP/1.1" 500 141976
INFO 2025-09-22 07:00:36,151 autoreload 68994 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/comments/serializers.py changed, reloading.
INFO 2025-09-22 07:00:38,332 autoreload 71173 8371577024 Watching for file changes with StatReloader
ERROR 2025-09-22 07:03:31,447 log 71173 6129086464 Internal Server Error: /api/v1/comments/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 1869, in to_representation
    method = getattr(self.parent, self.method_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CommentSerializer' object has no attribute 'get_replies_count'
ERROR 2025-09-22 07:03:31,463 basehttp 71173 6129086464 "GET /api/v1/comments/ HTTP/1.1" 500 141976
INFO 2025-09-22 07:04:40,779 autoreload 71173 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/comments/serializers.py changed, reloading.
INFO 2025-09-22 07:04:42,152 autoreload 72471 8371577024 Watching for file changes with StatReloader
INFO 2025-09-22 07:04:46,663 basehttp 72471 6164312064 "GET /api/v1/comments/ HTTP/1.1" 200 414
INFO 2025-09-22 07:06:00,538 basehttp 72471 6181138432 "GET /api/v1/comments/1/replies HTTP/1.1" 301 0
ERROR 2025-09-22 07:06:00,683 log 72471 6181138432 Internal Server Error: /api/v1/comments/1/replies/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CommentSerializer is not JSON serializable
ERROR 2025-09-22 07:06:00,691 basehttp 72471 6181138432 "GET /api/v1/comments/1/replies/ HTTP/1.1" 500 123611
ERROR 2025-09-22 07:06:06,930 log 72471 6181138432 Internal Server Error: /api/v1/comments/1/replies/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CommentSerializer is not JSON serializable
ERROR 2025-09-22 07:06:06,934 basehttp 72471 6181138432 "GET /api/v1/comments/1/replies/ HTTP/1.1" 500 123451
INFO 2025-09-22 07:06:55,186 basehttp 72471 6181138432 "POST /api/v1/comments/ HTTP/1.1" 201 130
ERROR 2025-09-22 07:07:11,682 log 72471 6181138432 Internal Server Error: /api/v1/comments/1/replies/
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/venv/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CommentSerializer is not JSON serializable
ERROR 2025-09-22 07:07:11,692 basehttp 72471 6181138432 "GET /api/v1/comments/1/replies/ HTTP/1.1" 500 126901
INFO 2025-09-22 07:11:05,802 autoreload 72471 8371577024 /Users/macbook/PycharmProjects/testapps/app-news-drf/app-news/apps/comments/views.py changed, reloading.
INFO 2025-09-22 07:11:09,116 autoreload 74524 8371577024 Watching for file changes with StatReloader
INFO 2025-09-22 07:11:11,198 basehttp 74524 6126448640 "GET /api/v1/comments/1/replies/ HTTP/1.1" 200 766
INFO 2025-09-22 07:11:56,641 basehttp 74524 6126448640 "GET /api/v1/comments/ HTTP/1.1" 200 769
